# Generated by Django 4.2.1 on 2023-05-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_product_id_alter_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.UUIDField(
                default="c15df34904b64fd9a46d2a08fdcb8ffc",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
