# Generated by Django 4.2.1 on 2023-05-26 08:42

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_product_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("objectss", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.UUIDField(
                default=uuid.UUID("eeb02b23-4b8b-440e-99f9-e60bea7a6863"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
