# Generated by Django 4.2.1 on 2023-06-11 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_product_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="prod_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="author",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.UUIDField(
                default=uuid.UUID("b9b8ec35-d407-4328-9692-818c383a1e3d"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
