# Generated by Django 4.2.1 on 2023-05-29 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_product_product_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.UUIDField(
                default=uuid.UUID("3db7b3d4-8746-4402-80e2-4985f08268ad"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
