# Generated by Django 4.2.1 on 2023-05-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
