# Generated by Django 4.2.1 on 2023-05-30 17:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_product_product_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0005_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartItem",
            new_name="Cart",
        ),
    ]
