# Generated by Django 4.2.1 on 2023-05-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_rename_cartitem_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
